### ISSUE TITLE
--node switch seems broken

### ISSUE THREAD

**Issue by algesten** [h2non/nar#117]
```
$ nar -V
0.3.20
```

```
sultana$ nar create --debug --executable --node 5.0.0
Error: Invalid node version '5.0.0'
    at setNode (/usr/local/lib/node_modules/nar/lib/create-exec.js:258:13)
    at apply (/usr/local/lib/node_modules/nar/lib/create-exec.js:201:3)
```

```
sultana$ nar create --executable --node 4.2.2
Error: Invalid node version '4.2.2'
```

```
sultana$ nar create --executable --node latest
Creating archive...
Add [dependency] fnuc
...
Downloading binary...
Error: Invalid response code: 404 Not Found
```

Am I perhaps misunderstanding how this switch works?

**Comment by h2non** [comment]
Fixed. Just update `nar` to version `0.3.21`:
```bash
npm update -g nar
```

Bug explanation: `nar` supports newest node versions, but those code changes has not been pushed as  `npm`  release. Now it does. 

Thank you for reporting.
